name: Pull Request Workflow

on: 
  pull_request:
    branches: main

jobs:
  development-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: my-branch

      - name: Create version
        uses: paulhatch/semantic-version@v4.0.2
        id: version
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "v${major}.${minor}.${patch}-prerelease${increment}"
          bump_each_commit: false
          search_commit_body: false

      - name: Print Version
        run: echo ${{ steps.version.outputs.version}}
 